Orolia2s/oscillatord

src/monitoring.c, tests/monitoring_client.c
Config:
```
monitoring=true
socket-address=0.0.0.0
socket-port=2958
oscillator=dummy
gnss-device-tty=/dev/ttyS4
gnss-receiver-reconfigure=true
ptp-clock=/dev/ptp2
```
Before:
```
ss -lnp | grep -i osci
tcp     LISTEN   0        1                                             0.0.0.0:36363                                              0.0.0.0:*                     users:(("oscillatord",pid=68329,fd=3))                                         
```
After:
```
ss -lnp | grep -i osci
tcp     LISTEN   0        1                                             0.0.0.0:2958                                               0.0.0.0:*                     users:(("oscillatord",pid=144162,fd=3))                                        
```
=> monitoring: fix listening port

src/oscillatord.c
When the disciplining is disabled and only the monitoring is enabled, the queries to the clock are very aggressive in a for loop without a sleep.
Should those queries be less aggressive in such cases?
=> less agressive clock query

src/oscillators/sa5x_oscillator.c
Change version request command to escape from possible SA3xm compatibility
mode. This request is the first command to MAC which is issued during
initialisation phase. It should be escaped with back-slash character
to return to C3 commands on SA5x. And also fix style issues while here.
=> sa5x: change software version command

src/oscillators/sa5x_oscillator.c
sscanf always adds 0x0 to the end of the parsed string and it will overload buffers allocated to serial number and software version. even though it will not corrupt any actual data (alignment will hide the problem), GNU mcheck finds this problems and aborts on next allocation.
=> sa5x: fix off-by-one in reading serial number

src/oscillatord.c
The monitoring of phase offset was changed when jumping to v3.0.x but was not correctly upgraded during previous PR.
This one fixes the problem and phase offset is now correctly returned in monitoring socket
=> sa5x: v3.0.x update phase error monitoring

src/gnss.c, src/gnss.h, src/oscillator.c, src/oscillator.h, src/oscillatord.c, src/oscillators/sa5x_oscillator.c
Some more information about GNSS status should be provided to SA5x monitoring module to better describe current Clock Class and Clock Accuracy
=> SA5x: Provide GNSS information to better control disciplining status

src/oscillators/sa5x_oscillator.c
While startup SA5x is in calibrating status and will go to uncalibrated once there is no GNSS signal
=> sa5x: change starting clock class to CALIBRATING

src/oscillators/sa5x_oscillator.c
New version of oscillatord has more information of disciplining status.
Add these values to SA5x to report.
Signed-off-by: Vadim Fedorenko <vadfed@fb.com>
=> sa5x: provide more status info

src/oscillators/mRo50_oscillator.c
reset command may not be understood if mRO previously received an incomplete message from another process (minicom for example)
Re sending the command make sure mRo does not block
=> Resend reset command to mRo50 if command has not been understood by mRO

src/oscillators/sa5x_oscillator.c
Previously SA5x oscillator will not show that it's back from
holdover state until the second stage of calibration is reached.
But it can indicate better because there is special clock class
for such situation.
Signed-off-by: Vadim Fedorenko <vadfed@fb.com>
=> SA5x: Recover from holdover when GNSS is back

src/oscillatord.c, src/oscillators/sa5x_oscillator.c
There is no reason to store any disciplining values in EEPROM if oscillatord is running in monitoring mode. Move the logic to a proper position.
Signed-off-by: Vadim Fedorenko <vadfed@fb.com>
=> oscillatord: improve saving disciplining in EEPROM

src/monitoring.c, src/monitoring.h, src/oscillatord.c, src/oscillators/sa5x_oscillator.c
We have seen problems with SA53 going out of range of precise tuning and needs latch command to be issued. But the alarm regarding the issue is not stable. This PR adds logic to issue latch command even if there is no alarm.
Another commit fixing race condition and possible null-pointer resolution while initialising monitoring thread.
=> SA53 improve latching behaviour 

CMakeLists.txt
This function is called in some source files.  Before this change, this compiled only on compilers which support implicit function declarations, a feature that was removed from the C language in 1999.
Related to:
<https://fedoraproject.org/wiki/Changes/PortingToModernC>
<https://fedoraproject.org/wiki/Toolchain/PortingToModernC>
=> Build with -D_GNU_SOURCE for a declaration of clock_adjtime in <time.h>

src/gnss.c
With latests update to ubloxcfcg UBX_TIME_TP_V0_GROUP0_t was replaced with UBX_TIM_TP_V0_GROUP0_t. The only way to check it is to check for definition of UBX_TIM_TM2_V0_SIZE which was introduced with the same commit.
Signed-off-by: Vadim Fedorenko <vadfed@fb.com>
=> gnss: update to use new version of ubxlocfg

src/oscillators/sa5x_oscillator.c
We found out that right after restart `gnss` is being unstable and having a relatively large TAU (50) significantly impacts the time to lock/stabilize the phase. Setting TAU to 10 leads to a faster convergence of phase which leads to a faster sa53 lock state (less than 20 minutes)
=> [sa53] set first TAU to 10

src/oscillatord.c, src/oscillators/sa5x_oscillator.c
We have some issues with reading from GNSS port which ends up having one second of no GNSS fix and move SA53 to holdover. It looks like the issue is related to serial port rather then GNSS because SA53 can see the PPS-in signal. Skip transition to HOLDOVER status in such case.
Also fix some uninitialized usage of variables around GNSS.
=> sa5x: don't go to HOLDOVER when GNSS port times out

src/gnss.c
Once Survey-in is not active, the values won't change. No need to spam the same information every second.
=> gnss: stop spamming debug info of inactive survey-in

src/oscillators/sa5x_oscillator.c
To check the HOLDOVER duration we compare the timestamp of the last known GNSS fix and current time and use this comparison to adjust the state of the card and MAC. Unfortunately, the last known GNSS fix timestamp was stored as UTC time came from GNSS, but later compared to monotonic clock timestamp. This comparison is incorrect. Store monotonic clock timestamp every time we recieve good GNSS time and use it later in all comparisons.
=> sa53: adjust GNSS fix calculations

src/gnss.c, src/gnss.h, src/monitoring.c, src/monitoring.h, src/oscillator.h, src/oscillatord.c
Reduce the scope of monitoring mutex lock and move GNSS monitoring under another mutex with GNSS thread filling the data.
=> Monitoring rework

src/monitoring.c, utils/art_monitoring_client.c
=> Refactor socket creation to support IPv6
